### ISSUE TITLE
Sugestões de melhoria para o onboarding de novos devs

### ISSUE THREAD

**Issue by SecretX33** [fredlinhares/yet_another_fighting_game#1]
Aqui seguem algumas sugestões de melhoria, isso é, após eu testar o projeto, senti algumas dores que não teriam ocorrido no caso de haver explicação de como fazer algumas coisas em algum arquivo de documentação, no próprio repositório.

# 1. Passo a passo de como configurar a máquina do desenvolvedor

Um passo a passo de instalação que realmente "pega na mão" do desenvolvedor, saindo realmente de uma máquina "limpa" para uma máquina com todas as dependências instaladas. Minha suguestão de passos seria algo do tipo:

- Instalando GCC (MSYS2 no Windows)
- Instalando Ruby
- Instalando Rake

Junto de uma explicação bem resumida do _por quê_ estamos instalando cada um desses itens. Por exemplo:

## 1. Instalando GCC (MSYS2 no Windows)

É necessário instalar o GCC pois ele é o compilador de C++ que usaremos nesse projeto.

{{Instruções de como instalar o GCC aqui no Linux e no Windows aqui}}

## 2. Instalando Ruby

Instalar o Ruby é necessário pois o Rake, a ferramenta que vamos usar para gerenciar os builds do projeto, é escrita em Ruby, e portanto precisamos instalar o runtime da linguagem.

{{Instruções de como instalar o Ruby aqui no Linux e no Windows aqui}}

## 3. Instalando Rake

Rake será a ferramenta de gerenciamento de build que usaremos para buildar o projeto. O Rake foi escolhido por causa de blah blah blah...

{{Instruções de como instalar o Rake aqui no Linux e no Windows aqui}}

# 2. Problemas com `libSDL`

O segundo problema que eu gostaria de compartilhar foi o de usar/instalar a libSDL, que é assumido já estar instalado no computador do desenvolvedor (já que foi importado nos arquivos fonte usando `<>`), e não existe nenhuma instrução de como instalar essa library caso ele já não a tenha. 

Fui tentar rodar o projeto no Windows e simplesmente não consegui pois emperrei nesse ponto. Não tenho muita familiaridade com as linguagens C em geral, e portanto, eu não sei como se instala a libSDL. Tenho certeza que deve ser um processo relativamente simples, tendo em vista que consegui baixar os `.h` da library, e também consegui baixar o arquivo `.dll`, só não sei como eu "junto" o projeto com o arquivo `.dll` para que o GCC faça o link estático das funções dos arquivos `.h` da libSDL com o arquivo `.dll`.

# 3. Reproducible builds

Também gostaria de aproveitar esse ponto para sugerir uma mudança que seria *excelente* para melhorar a experiência de novos desenvolvedores (como eu): 

Incluir _todos_ os arquivos fonte necessários para compilar o projeto _diretamente_ no repositório, para que a compilação do projeto siga sem depender de nenhuma dependência externa mágica (sempre que possível). Sendo um pouco mais específico, minha sugestão seria incluir todas as configurações e arquivos necessários da libSDL, de forma que o projeto possa ser compilado em qualquer sistema operacional, sem a necessidade de instalar manualmente _nenhum_ arquivo extra da libSDL.

O nome desse conceito é "Reproducible builds", e a definição é: "Reproducible builds, also known as deterministic compilation, is a process of compiling software which ensures the resulting binary code can be reproduced. Source code compiled using deterministic compilation will always output the same binary."

Veja mais aqui: https://en.wikipedia.org/wiki/Reproducible_builds

------
E é isso, esse é meu feedback, os problemas que eu enfrentei tentando rodar o projeto, e minhas sugestões de melhoria. Uma vez que eu consiga resolver esse problema da `libSDL` (com a ajuda de vocês), eu sigo para o teste do projeto, e trago mais feedbacks de melhoria.

**Comment by fredlinhares** [comment]
Resolvido pelo commit: ae0851f77cee220de14c111d4e854f35da76f5d3
